/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Timetable } from "./Timetable";
import { TimetableCountArgs } from "./TimetableCountArgs";
import { TimetableFindManyArgs } from "./TimetableFindManyArgs";
import { TimetableFindUniqueArgs } from "./TimetableFindUniqueArgs";
import { CreateTimetableArgs } from "./CreateTimetableArgs";
import { UpdateTimetableArgs } from "./UpdateTimetableArgs";
import { DeleteTimetableArgs } from "./DeleteTimetableArgs";
import { Student } from "../../student/base/Student";
import { TimetableService } from "../timetable.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Timetable)
export class TimetableResolverBase {
  constructor(
    protected readonly service: TimetableService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Timetable",
    action: "read",
    possession: "any",
  })
  async _timetablesMeta(
    @graphql.Args() args: TimetableCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Timetable])
  @nestAccessControl.UseRoles({
    resource: "Timetable",
    action: "read",
    possession: "any",
  })
  async timetables(
    @graphql.Args() args: TimetableFindManyArgs
  ): Promise<Timetable[]> {
    return this.service.timetables(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Timetable, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Timetable",
    action: "read",
    possession: "own",
  })
  async timetable(
    @graphql.Args() args: TimetableFindUniqueArgs
  ): Promise<Timetable | null> {
    const result = await this.service.timetable(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Timetable)
  @nestAccessControl.UseRoles({
    resource: "Timetable",
    action: "create",
    possession: "any",
  })
  async createTimetable(
    @graphql.Args() args: CreateTimetableArgs
  ): Promise<Timetable> {
    return await this.service.createTimetable({
      ...args,
      data: {
        ...args.data,

        student: args.data.student
          ? {
              connect: args.data.student,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Timetable)
  @nestAccessControl.UseRoles({
    resource: "Timetable",
    action: "update",
    possession: "any",
  })
  async updateTimetable(
    @graphql.Args() args: UpdateTimetableArgs
  ): Promise<Timetable | null> {
    try {
      return await this.service.updateTimetable({
        ...args,
        data: {
          ...args.data,

          student: args.data.student
            ? {
                connect: args.data.student,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Timetable)
  @nestAccessControl.UseRoles({
    resource: "Timetable",
    action: "delete",
    possession: "any",
  })
  async deleteTimetable(
    @graphql.Args() args: DeleteTimetableArgs
  ): Promise<Timetable | null> {
    try {
      return await this.service.deleteTimetable(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Student, {
    nullable: true,
    name: "student",
  })
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "any",
  })
  async getStudent(
    @graphql.Parent() parent: Timetable
  ): Promise<Student | null> {
    const result = await this.service.getStudent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
