/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AdmissionLetterService } from "../admissionLetter.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AdmissionLetterCreateInput } from "./AdmissionLetterCreateInput";
import { AdmissionLetter } from "./AdmissionLetter";
import { AdmissionLetterFindManyArgs } from "./AdmissionLetterFindManyArgs";
import { AdmissionLetterWhereUniqueInput } from "./AdmissionLetterWhereUniqueInput";
import { AdmissionLetterUpdateInput } from "./AdmissionLetterUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AdmissionLetterControllerBase {
  constructor(
    protected readonly service: AdmissionLetterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AdmissionLetter })
  @nestAccessControl.UseRoles({
    resource: "AdmissionLetter",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAdmissionLetter(
    @common.Body() data: AdmissionLetterCreateInput
  ): Promise<AdmissionLetter> {
    return await this.service.createAdmissionLetter({
      data: {
        ...data,

        student: data.student
          ? {
              connect: data.student,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AdmissionLetter] })
  @ApiNestedQuery(AdmissionLetterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AdmissionLetter",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async admissionLetters(
    @common.Req() request: Request
  ): Promise<AdmissionLetter[]> {
    const args = plainToClass(AdmissionLetterFindManyArgs, request.query);
    return this.service.admissionLetters({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AdmissionLetter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdmissionLetter",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async admissionLetter(
    @common.Param() params: AdmissionLetterWhereUniqueInput
  ): Promise<AdmissionLetter | null> {
    const result = await this.service.admissionLetter({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AdmissionLetter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdmissionLetter",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAdmissionLetter(
    @common.Param() params: AdmissionLetterWhereUniqueInput,
    @common.Body() data: AdmissionLetterUpdateInput
  ): Promise<AdmissionLetter | null> {
    try {
      return await this.service.updateAdmissionLetter({
        where: params,
        data: {
          ...data,

          student: data.student
            ? {
                connect: data.student,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AdmissionLetter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdmissionLetter",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAdmissionLetter(
    @common.Param() params: AdmissionLetterWhereUniqueInput
  ): Promise<AdmissionLetter | null> {
    try {
      return await this.service.deleteAdmissionLetter({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
