/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AcceptanceLetterService } from "../acceptanceLetter.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AcceptanceLetterCreateInput } from "./AcceptanceLetterCreateInput";
import { AcceptanceLetter } from "./AcceptanceLetter";
import { AcceptanceLetterFindManyArgs } from "./AcceptanceLetterFindManyArgs";
import { AcceptanceLetterWhereUniqueInput } from "./AcceptanceLetterWhereUniqueInput";
import { AcceptanceLetterUpdateInput } from "./AcceptanceLetterUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AcceptanceLetterControllerBase {
  constructor(
    protected readonly service: AcceptanceLetterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AcceptanceLetter })
  @nestAccessControl.UseRoles({
    resource: "AcceptanceLetter",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAcceptanceLetter(
    @common.Body() data: AcceptanceLetterCreateInput
  ): Promise<AcceptanceLetter> {
    return await this.service.createAcceptanceLetter({
      data: {
        ...data,

        student: data.student
          ? {
              connect: data.student,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AcceptanceLetter] })
  @ApiNestedQuery(AcceptanceLetterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AcceptanceLetter",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async acceptanceLetters(
    @common.Req() request: Request
  ): Promise<AcceptanceLetter[]> {
    const args = plainToClass(AcceptanceLetterFindManyArgs, request.query);
    return this.service.acceptanceLetters({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AcceptanceLetter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AcceptanceLetter",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async acceptanceLetter(
    @common.Param() params: AcceptanceLetterWhereUniqueInput
  ): Promise<AcceptanceLetter | null> {
    const result = await this.service.acceptanceLetter({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AcceptanceLetter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AcceptanceLetter",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAcceptanceLetter(
    @common.Param() params: AcceptanceLetterWhereUniqueInput,
    @common.Body() data: AcceptanceLetterUpdateInput
  ): Promise<AcceptanceLetter | null> {
    try {
      return await this.service.updateAcceptanceLetter({
        where: params,
        data: {
          ...data,

          student: data.student
            ? {
                connect: data.student,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AcceptanceLetter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AcceptanceLetter",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAcceptanceLetter(
    @common.Param() params: AcceptanceLetterWhereUniqueInput
  ): Promise<AcceptanceLetter | null> {
    try {
      return await this.service.deleteAcceptanceLetter({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
